name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAR_NAME: Connect4.jar
      OUT_DIR: out

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Compile and Package to JAR
      run: |
        mkdir $OUT_DIR
        javac -d $OUT_DIR src/*.java
        jar cvfm $OUT_DIR/$JAR_NAME customManifest.txt -C $OUT_DIR .

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Connect4-jar
        path: ./out/${{ env.JAR_NAME }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}

  windows_build:
    needs: build
    runs-on: windows-latest
    env:
      JAR_NAME: Connect4.jar
      OUT_DIR: out

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR from artifact
      uses: actions/download-artifact@v2
      with:
        name: Connect4-jar
        path: ./out/

    - name: Setup Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Create Standalone for Windows
      run: jpackage --input ${{ env.OUT_DIR }} --name Connect4 --main-jar ${{ env.JAR_NAME }} --main-class src.App --type exe

    - name: Attach Windows Standalone to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build.outputs.release_upload_url }}
        asset_path: ./Connect4.exe
        asset_name: Connect4-Windows.exe
        asset_content_type: application/octet-stream

  mac_build:
    needs: build
    runs-on: macOS-latest
    env:
      JAR_NAME: Connect4.jar
      OUT_DIR: out

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR from artifact
      uses: actions/download-artifact@v2
      with:
        name: Connect4-jar
        path: ./out/

    - name: Setup Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Create Standalone for macOS
      run: jpackage --input ${{ env.OUT_DIR }} --name Connect4 --main-jar ${{ env.JAR_NAME }} --main-class src.App --type dmg

    - name: Attach macOS Standalone to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build.outputs.release_upload_url }}
        asset_path: ./Connect4.dmg
        asset_name: Connect4-MacOS.dmg
        asset_content_type: application/octet-stream

  ubuntu_build:
    needs: build
    runs-on: ubuntu-latest
    env:
      JAR_NAME: Connect4.jar
      OUT_DIR: out

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR from artifact
      uses: actions/download-artifact@v2
      with:
        name: Connect4-jar
        path: ./out/

    - name: Setup Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Create Standalone for Ubuntu
      run: jpackage --input ${{ env.OUT_DIR }} --name Connect4 --main-jar ${{ env.JAR_NAME }} --main-class src.App --type deb

    - name: Attach Ubuntu Standalone to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build.outputs.release_upload_url }}
        asset_path: ./Connect4.deb
        asset_name: Connect4-Ubuntu.deb
        asset_content_type: application/octet-stream

