name: Build and Release JAR & Standalone Apps

on:
  push:
    tags:
      - 'v*.*.*' # Trigger for version tags

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAR_NAME: Connect4.jar

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'  # We need Java 16 for jpackage
        distribution: 'temurin'

    - name: Compile Java files
      run: |
        mkdir bin
        javac -d ./bin ./src/*.java

    - name: Package into JAR
      run: |
        jar cvmf ${{ github.workspace }}/customManifest.txt ${{ env.JAR_NAME }} -C bin/ .

    - name: Create Standalone for Mac
      run: jpackage --input . --name Connect4 --main-jar ${{ env.JAR_NAME }} --main-class src.App

    - name: Create Standalone for Ubuntu
      run: jpackage --input . --name Connect4 --main-jar ${{ env.JAR_NAME }} --main-class src.App --type deb

    - name: Create Standalone for Windows
      run: jpackage --input . --name Connect4 --main-jar ${{ env.JAR_NAME }} --main-class src.App --type exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Attach JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.JAR_NAME }}
        asset_name: ${{ env.JAR_NAME }}
        asset_content_type: application/java-archive

    - name: Attach Mac Standalone to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Connect4.app
        asset_name: Connect4-Mac.app
        asset_content_type: application/octet-stream

    - name: Attach Ubuntu Standalone to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Connect4.deb
        asset_name: Connect4-Ubuntu.deb
        asset_content_type: application/octet-stream

    - name: Attach Windows Standalone to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Connect4.exe
        asset_name: Connect4-Windows.exe
        asset_content_type: application/octet-stream
