name: Build and Release JAR

on:
  push:
    tags:
      - 'v*.*.*' # This will trigger the workflow only for tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    # Declare JAR_NAME as an environment variable
    env:
      JAR_NAME: Connect4.jar

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  
        distribution: 'temurin'

    - name: Compile Java files
      run: |
        mkdir bin
        javac -d ./bin ./src/*.java

    - name: Package into JAR
      run: |
        jar cvmf ${{ github.workspace }}/customManifest.txt ${{ env.JAR_NAME }} -C bin/ .

    - name: Set JAR executable permission
      run: chmod +x ${{ env.JAR_NAME }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Attach JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.JAR_NAME }}
        asset_name: ${{ env.JAR_NAME }}
        asset_content_type: application/java-archive
